baseURL = "https://aistars26.github.io/stmfork/"
languageCode = "en-us"
title = "The Ultimate Stabat Mater Website"

[params]
  subtitle = "a musical journey through the ages"
  description = "Proof of concept for a Hugo/GitHub Pages version of the Stabat Mater website."
  noindex = true

[taxonomies]
  country = "countries"
  period = "periods"

[menu]
  [[menu.main]]
    name = "Composers"
    url = "/composers/"
    weight = 1
    identifier = "composers"
  [[menu.main]]
    name = "Alphabetically"
    url = "/composers/"
    weight = 1
    parent = "composers"
  [[menu.main]]
    name = "By country of origin"
    url = "/countries/"
    weight = 2
    parent = "composers"
  [[menu.main]]
    name = "Chronologically"
    url = "/periods/"
    weight = 3
    parent = "composers"
  [[menu.main]]
    name = "By duration"
    url = "/composers/"
    weight = 4
    parent = "composers"
  [[menu.main]]
    name = "Texts"
    url = "/texts/"
    weight = 2
  [[menu.main]]
    name = "Translations"
    url = "/translations/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Missing CDs"
    url = "/contact/"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6
  [[menu.main]]
    name = "Donate?"
    url = "/contact/"
    weight = 7
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8
